### ISSUE TITLE
make Server error

### ISSUE THREAD

**Issue by Volk-khan** [mr-pandabear/bamboo#20]
![image](https://user-images.githubusercontent.com/87937901/148298035-a1b9352e-f70e-4946-af88-6761649a7d9e.png)

**Comment by mr-pandabear** [comment]
Do the following
```
rm -rf data
mkdir data
chmod +rw data
./bin/server --testnet
```

**Comment by Volk-khan** [comment]
at what stage is the project? testnet or mainnet?

**Comment by Volk-khan** [comment]
how i can see my balance at wallet?

**Comment by Volk-khan** [comment]
![image](https://user-images.githubusercontent.com/87937901/148446063-89ab9a16-17a1-4317-af66-b3b9170e885c.png)

**Comment by mr-pandabear** [comment]
This means you don't have levelDB installed. Are you running Ubuntu or CentOS? You might want to look at the install scripts for each:
https://github.com/mr-pandabear/panda-utils/blob/master/test-node-centos.sh
https://github.com/mr-pandabear/panda-utils/blob/master/test-node-ubuntu.sh
If running ubuntu:
```sudo apt-get -y install libleveldb-dev```

If running centos you'd want to run:
```
wget https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/l/leveldb-1.22-1.el8.x86_64.rpm
sudo yum localinstall -y leveldb-1.22-1.el8.x86_64.rpm
wget https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/l/leveldb-devel-1.22-1.el8.x86_64.rpm
sudo yum localinstall -y leveldb-devel-1.22-1.el8.x86_64.rpm
sudo mkdir /usr/lib/x86_64-linux-gnu
sudo cp /usr/lib64/libleveldb.so.1.22.0 /usr/lib/x86_64-linux-gnu/libleveldb.so
```

**Comment by mr-pandabear** [comment]
To see your wallet balance on mainnet go here:
http://ec2-34-218-176-84.us-west-2.compute.amazonaws.com/wallet?host=http://ec2-54-189-82-240.us-west-2.compute.amazonaws.com:3000

You can paste in your wallet address into the search box and see it. The wallet address can be found by opening the keys.json file in a text editor and is printed when you start up the miner.

**Comment by Volk-khan** [comment]
![image](https://user-images.githubusercontent.com/87937901/148554220-996fd8b9-98ee-4c42-a103-e2df75e44932.png)
![image](https://user-images.githubusercontent.com/87937901/148554291-3c62d126-3f1e-4b37-ac18-8c28a153c743.png)

**Comment by Volk-khan** [comment]
is  this algoritm ASIC frendly?

**Comment by Volk-khan** [comment]
whats algo?

**Comment by mr-pandabear** [comment]
Okay nice... so it's building. You need to make a directory called "data", make sure you run with --testnet as the mainnet is not compatible with the master branch right now.

Algorithm is a custom one based on SHA256, it is not ASIC resistant, though there are no GPU or ASIC implementations at the moment.

**Comment by mr-pandabear** [comment]
Please use discord or telegram for build help!

**Comment by Volk-khan** [comment]
![image](https://user-images.githubusercontent.com/87937901/148704963-8a3e6d47-3de8-4a5a-957f-27a87762b765.png)
Awesome!
