### ISSUE TITLE
BLOCK_TIMESTAMP_TOO_OLD rejects on new windows release

### ISSUE THREAD

**Issue by DrKiz** [mr-pandabear/bamboo#22]
![Capture](https://user-images.githubusercontent.com/87797150/148661207-54af9d6a-fb6a-4445-9253-46b1924c32b3.PNG)

**Comment by DrKiz** [comment]
Resolved.  Time slightly out of sync on computer.  Syncing time resolved it.

**Comment by Volk-khan** [comment]
do you have Windows?
