### ISSUE TITLE
Where is my coins?

### ISSUE THREAD

**Issue by Volk-khan** [mr-pandabear/bamboo#25]
few hours ago i had 82650 BMB on 00D368B6A8C88D240D43A92D05307A35588DE465B7C0DF94BB ,  but now i have 82400

**Comment by Volk-khan** [comment]
do you have Explorer?

**Comment by Volk-khan** [comment]
![image](https://user-images.githubusercontent.com/87937901/148706849-170b7d88-9785-4f61-8e98-59cc6cd04e37.png)
Great work! Awesome!

**Comment by mr-pandabear** [comment]
Please use discord for these sorts of questions. There was a chain fork at block ~125900 so if you earned after it may be gone. 

You can click "Check Wallet Balance" on this link:
http://ec2-34-218-176-84.us-west-2.compute.amazonaws.com/

**Comment by Volk-khan** [comment]
> Please use discord for these sorts of questions. There was a chain fork at block ~125900 so if you earned after it may be gone.
if I had a discord address ....... I would go there and ask questions, where can I get the link if you haven't published it ??
